import Header from '@/src/component/header/header';
import '@/src/styles/globals.scss';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import localFont from 'next/font/local';

const bueno = localFont({
    src: '../../../public/fonts/bueno.woff2',
});

export const metadata: Metadata = {
    title: 'Remi Taniel - Portfolio',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={bueno.className}>
                <NextIntlClientProvider>
                    <Header />
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
